version: '3.8'

services:
  mongodb:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    volumes:
      - mongoDBData:/data/db
    networks:
      - mongoNet

networks:
  mongoNet:
    driver: bridge
volumes:
  mongoDBData:
